# ===============================
# ========  Utils config ========
# ===============================
authy:
  access-token:
    expiration-in-min: 5
  refresh-token:
      expiration-in-min: 10
  cookie:
    max-age-in-days: 1